In [1]:
import numpy as np
import time

#Autor: Pablo Sepúlveda Navarrete
#psepulveda2018@udec.cl
#En un archivo excel pasar la matriz correspondiente al problema
#No dejar espacios vacíos, rellenar con 0's
#¿Cómo rellenar con 0 en Excel? CTRL+I-->"especial"-->Celdas en blanco-->Escribir 0--->CTRL+ENTER-->Magia
#Guardar el archivo excel en formato csv
#Dejar el archivo .csv en la misma carpeta que el código
#Ejecutar el código
#La primera fila de las matrices que entrega el código corresponde a las filas entregadas por el problema
#La última columna de las matrices que entrega el código corresponde a las columnas entregadas por el problema
#Las filas y columas solo pueden ser números, si son letras se cae :(
#OJO: fijarse que el archivo .csv no contenga ';' demás


f = open('ProblemaDSP.csv','r')
linea = f.readline().rstrip().split(';')
columna= [int(linea[i]) for i in range(1,len(linea))]
fila = []
lista= []
while True:
    linea = f.readline().rstrip().split(';')
    if linea==['']:
        break
    fila.append(int(linea[0]))
    hola = []
    for i in range(1,len(linea)):
        hola.append(int(linea[i]))
    lista.append(hola)
    
f.close()
    
ncolumnas = len(lista[0])
nfilas = len(lista)


mantener_ordenfilas = [i for i in range(nfilas)]
mantener_ordencolumnas = [i for i in range(ncolumnas)]


filas = [2**(nfilas-i) for i in range(1,nfilas+1)]#Se está usando exponentes de 2 para hacer el método, en forma decreciente
columnas = [2**(ncolumnas-i) for i in range(1,ncolumnas+1)]


lista = np.array(lista)

paraimprimir = lista[:]
    
paraimprimir = np.append(paraimprimir, np.swapaxes([mantener_ordenfilas],0,1)+1 , axis=1)
mantener_ordencolumnasimprimir = np.array(mantener_ordencolumnas)+1
    
print('',mantener_ordencolumnasimprimir)  
print(paraimprimir)    

def sumafilas(lista,filas,columnas):
    rfilas = []
    for i in range(len(filas)):
        valor = 0
        for j in range(len(columnas)):
            valor += lista[i][j]*columnas[j]
        rfilas.append(valor)
    return rfilas

def sumacolumnas(lista,filas,columnas):
    rcolumnas = []
    contador = 0
    for i in range(len(columnas)):
        valor=0
        for j in range(len(filas)):
            valor+= lista[j][contador]*filas[j]
        contador+=1
        rcolumnas.append(valor)
    return rcolumnas

inicioTiempo = time.time()#Contador de tiempo

while True:
    sumafila = sumafilas(lista,filas,columnas)
    rfilas = [[sumafila[i],mantener_ordenfilas[i],i] for i in range(len(filas))]
    #print('rfilas',rfilas)
    
    rfilas_ordenada = sorted(rfilas,reverse=True,key = lambda x:x[0])
    #print('rfilas ordenada',rfilas_ordenada)
    
    if rfilas!=rfilas_ordenada:
        print('Se ordenaron las filas')
    else:
        print('Se mantuvieron las filas')
        print('El algoritmo terminó')
        break
        
    
    new_ordenfilas = [rfilas_ordenada[i][2] for i in range(len(filas))]

    mantener_ordenfilas = [rfilas_ordenada[i][1] for i in range(len(filas))]
    lista = lista[new_ordenfilas,:]
    
    paraimprimir = lista[:]
    
    paraimprimir = np.append(paraimprimir, np.swapaxes([mantener_ordenfilas],0,1)+1 , axis=1)
    mantener_ordencolumnasimprimir = np.array(mantener_ordencolumnas)+1
    
    print('',mantener_ordencolumnasimprimir)  
    print(paraimprimir)
    
    
    sumacolumna = sumacolumnas(lista,filas,columnas)
    rcolumnas = [[sumacolumna[i],mantener_ordencolumnas[i],i] for i in range(len(columnas))]
    
    #print('rcolumnas',rcolumnas)
    
    rcolumnas_ordenada = sorted(rcolumnas,reverse=True,key=lambda x:x[0])
    
    #print('rcolumnas ordenada',rcolumnas_ordenada)
    if rcolumnas!=rcolumnas_ordenada:
        print('Se ordenaron las columnas')
    else:
        print('Se mantuvieron las columnas')
        print('El algoritmo terminó')
        break
        

    new_ordencolumnas = [rcolumnas_ordenada[i][2] for i in range(len(columnas))]

    mantener_ordencolumnas = [rcolumnas_ordenada[i][1] for i in range(len(columnas))]
    

    lista = lista[:,new_ordencolumnas]
    
    paraimprimir = lista[:]
    
    paraimprimir = np.append(paraimprimir, np.swapaxes([mantener_ordenfilas],0,1)+1 , axis=1)
    mantener_ordencolumnasimprimir = np.array(mantener_ordencolumnas)+1
    
    print('',mantener_ordencolumnasimprimir)
    print(paraimprimir)
      
    

finalTiempo = time.time()


tiempo = finalTiempo - inicioTiempo
print('El algoritmo se demoró',tiempo,'segundos')

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  0  0  0  0  0  0  0  0  1  0  1  0  0  1  1]
 [ 0  1  1  0  0  0  0  0  1  0  0  0  1  0  0  2]
 [ 1  0  0  1  0  0  1  1  0  0  1  0  0  0  0  3]
 [ 0  1  1  0  0  0  0  0  1  0  0  0  1  0  0  4]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  1  0  5]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  1  0  6]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  1  0  7]
 [ 0  1  1  0  0  0  0  0  1  0  0  0  1  0  0  8]
 [ 0  1  1  0  0  0  0  0  1  0  0  0  1  0  0  9]
 [ 0  0  0  0  0  0  0  0  0  1  0  1  0  0  1 10]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  1  0 11]
 [ 0  1  1  0  0  0  0  0  1  0  0  0  1  0  0 12]
 [ 1  0  0  1  0  0  1  1  0  0  1  0  0  0  0 13]
 [ 0  0  0  0  0  0  0  0  0  1  0  1  0  0  1 14]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  1  0 15]]
Se ordenaron las filas
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  0  0  1  0  0  1  1  0  0  1  0  0  0  0  3]
 [ 1  0  0  1  0  0  1  1  0  0  1  0  0  0  0 13]
 [ 0  1  1  0